using System;
using UnityEngine;
using FairyGUI;
using System.Collections;

namespace vitamin
{
    public class Vitamin : MonoBehaviour
    {
        public static Vitamin inst { get { return FindObjectOfType<Vitamin>(); } }

        [Header("åŸºæœ¬è®¾ç½®")]
        [CustomInspectorAttribute("UIæ˜¾ç¤ºè®¾ç½®")]
        public UIContentScaler uiScaler;

        [Header("ä¸Šä¸‹æ–‡")]
        [Tooltip("ç»§æ‰¿è‡ªvitamin.Contextçš„UIä¸Šä¸‹æ–‡")]
        [CustomInspectorAttribute("ç•Œé¢ä¸Šä¸‹æ–‡")]
        public Context uiContext;

        [Tooltip("ç»§æ‰¿è‡ªvitamin.Contextçš„ç©æ³•ä¸Šä¸‹æ–‡")]
        [CustomInspectorAttribute("ç©æ³•ä¸Šä¸‹æ–‡")]
        public Context gameContext;

        [Header("FPS")]
        [CustomInspectorAttribute("æ˜¾ç¤ºFPSç›‘æµ‹")]
        public bool fpsEnabled=false;

        [CustomInspectorAttribute("æ˜¾ç¤ºå†…å­˜ç›‘æµ‹")]
        public bool memoryEnabled = false;

        [CustomInspectorAttribute("æ˜¾ç¤ºè®¾å¤‡ä¿¡æ¯")]
        public bool deviceEnabled = false;

        [Header("è°ƒè¯•")]
        [CustomInspectorAttribute("é¢æ¿å‘¼å‡ºçƒ­é”®")]
        public KeyCode debugHotKey=KeyCode.F7;

        UIManager __ui;
        AudioManager __sound;
        BoardManager __bord;
        GuideManager __guide;
        ResManager __res;
        DebugManager __debug;
        public UIManager ui { get { return __ui; } }
        public AudioManager sound { get { return __sound; } }
        public BoardManager bord { get { return __bord; } }
        public GuideManager guide { get { return __guide; } }
        public ResManager res { get { return __res; } }
        public DebugManager debug { get { return __debug; } }
        internal EventEmitter __center_emitter;

        void Awake()
        {
            Injector.initialize(typeof(DebugCmdBase));

            __center_emitter = new EventEmitter();
            if (uiContext != null) uiContext.__emitter = __center_emitter;
            else Logger.Warn("UI Entry Not Found!");
            if (gameContext != null) gameContext.__emitter = __center_emitter;
            else Logger.Warn("Game Entry Not Found!");
            if (uiScaler == null) Logger.Warn("UIContentScalar Not Found!");

            __ui = gameObject.AddComponent<UIManager>();
            __sound = gameObject.AddComponent<AudioManager>(); 
            __bord = gameObject.AddComponent<BoardManager>();
            __guide = gameObject.AddComponent<GuideManager>();
            __res = gameObject.AddComponent<ResManager>();
            __debug = gameObject.AddComponent<DebugManager>();

            __ui.initialize();
            if (debugHotKey != KeyCode.None)
            {
                __debug.initialize(fpsEnabled, memoryEnabled, deviceEnabled, debugHotKey);
            }

            ui._emitter = __center_emitter;

            if (gameContext != null) gameContext.initialize();
            if (ui != null) uiContext.initialize();
            Logger.Info("ğŸ’ŠğŸ’ŠğŸ’Š ---------> Vitamin Start <--------- ğŸ’ŠğŸ’ŠğŸ’Š");
        }

        // Start is called before the first frame update
        void Start()
        {

        }

        // Update is called once per frame
        void Update()
        {

        }

        private void OnGUI()
        {
            ui.Resize();
        }


        protected void onUIEvent<T>(string type, EventHandler<T> handler) where T : vitamin.Event
        {
            __center_emitter.on<T>(type, handler);
        }


        protected void emitEvent<T>(string type, params object[] data) where T : vitamin.Event
        {
            __center_emitter.emit<T>(type, data);
        }

        public void callLater(Action method)
        {
            StartCoroutine(callLaterHandler(method));
        }

        IEnumerator callLaterHandler(Action method)
        {
            yield return new WaitForEndOfFrame();
            method.Invoke();
        }

        public void wait(float seconds, Action method)
        {
            StartCoroutine(waitHandler(seconds, method));
        }

        IEnumerator waitHandler(float seconds, Action method)
        {
            yield return new WaitForSeconds(seconds);
            method.Invoke();
        }
    }
}
